services:
  postgres:
    image: postgres:16-alpine
    container_name: ${STACK_NAME:-qls}-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-QLS_PROD}
      POSTGRES_USER: ${DB_USER:-qls_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-change-this-db-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_BIND_IP:-127.0.0.1}:${POSTGRES_PORT:-5432}:5432"
    networks:
      - qls-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-qls_user} -d ${DB_NAME:-QLS_PROD}"]
      interval: 10s
      timeout: 5s
      retries: 5


  qls-backend:
    image: ${BACKEND_IMAGE:-soramyo/qls-backend:latest}
    container_name: ${STACK_NAME:-qls}-backend
    restart: always
    ports:
      - "${BACKEND_PORT:-5078}:5078"
    environment:
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT:-Production}
      ASPNETCORE_URLS: http://+:5078
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${DB_NAME:-QLS_PROD};Username=${DB_USER:-qls_user};Password=${DB_PASSWORD:-change-this-db-password};Minimum Pool Size=1;Maximum Pool Size=20;Connection Idle Lifetime=300"
      Jwt__Key: ${JWT_KEY:-change-this-long-random-jwt-secret}
      Jwt__Issuer: QLS_Backend
      Jwt__Audience: QLS_Web
      Jwt__ExpireDays: 7
      CorsSettings__AllowedOrigins__0: ${CORS_ORIGIN_0:-http://localhost:5173}
      CorsSettings__AllowedOrigins__1: ${CORS_ORIGIN_1:-https://your-frontend-domain.com}
      CorsSettings__AllowedOrigins__2: ${CORS_ORIGIN_2:-https://h5.zdn.vn}
      CorsSettings__AllowedOrigins__3: ${CORS_ORIGIN_3:-https://h5.zadn.vn}
      Zalo__AppId: ${ZALO_APP_ID:-572235974883145642}
      Zalo__AppSecretKey: ${ZALO_APP_SECRET_KEY:-}
      Loyalty__MiniAppClaimUrlTemplate: ${LOYALTY_MINI_APP_CLAIM_URL_TEMPLATE:-https://zalo.me/s/572235974883145642?claimToken={token}}
      Zigbee2Mqtt__Host: ${MQTT_HOST:-localhost}
      Zigbee2Mqtt__Port: ${MQTT_PORT:-1883}
      LgApi__BaseUrl: https://kic-laundry.lgthinq.com/status/
      LgApi__ApiKey: vV6bStCpqr5Hqxbcr8Kmp9XkFh4VdlVp568YxBp5
      LgApi__AppVer: "0.1"
      LgApi__ClientType: USER
      LgApi__CountryCode: VN
      LgApi__ClientId: "12345"
      LgApi__ServiceCode: CHN000035
      LgApi__ServicePhase: OP
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - qls-network

volumes:
  postgres_data:
    name: ${STACK_NAME:-qls}-postgres-data

networks:
  qls-network:
    name: ${STACK_NAME:-qls}-network
    driver: bridge

