// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLS.Backend.Data;

#nullable disable

namespace QLS.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260401045211_AddMachineSessionsTable")]
    partial class AddMachineSessionsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLS.Backend.Models.Machine", b =>
                {
                    b.Property<string>("MachineId")
                        .HasColumnType("text");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("MachineId");

                    b.HasIndex("StoreId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("QLS.Backend.Models.MachineSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MachineId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("StoreId");

                    b.ToTable("MachineSessions");
                });

            modelBuilder.Entity("QLS.Backend.Models.Store", b =>
                {
                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("StoreId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("QLS.Backend.Models.StoreSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DryerGracePeriodMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("DryerMinInitialMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("DryerStepMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("DryerStepPrice")
                        .HasColumnType("numeric");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoreId")
                        .IsUnique();

                    b.ToTable("StoreSettings");
                });

            modelBuilder.Entity("QLS.Backend.Models.Machine", b =>
                {
                    b.HasOne("QLS.Backend.Models.Store", "Store")
                        .WithMany("Machines")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QLS.Backend.Models.MachineSession", b =>
                {
                    b.HasOne("QLS.Backend.Models.Machine", "Machine")
                        .WithMany("Sessions")
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLS.Backend.Models.Store", "Store")
                        .WithMany("MachineSessions")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QLS.Backend.Models.StoreSetting", b =>
                {
                    b.HasOne("QLS.Backend.Models.Store", "Store")
                        .WithOne("StoreSetting")
                        .HasForeignKey("QLS.Backend.Models.StoreSetting", "StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QLS.Backend.Models.Machine", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("QLS.Backend.Models.Store", b =>
                {
                    b.Navigation("MachineSessions");

                    b.Navigation("Machines");

                    b.Navigation("StoreSetting");
                });
#pragma warning restore 612, 618
        }
    }
}
