// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QLS.Backend.Data;

#nullable disable

namespace QLS.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260425100756_AddSuperWashToMachineSetting")]
    partial class AddSuperWashToMachineSetting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QLS.Backend.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid?>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("StoreId");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("QLS.Backend.Models.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Logo")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("QLS.Backend.Models.BrandLgCredential", b =>
                {
                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .HasColumnType("text");

                    b.Property<string>("LgEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LgUserNo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Oauth2BackendUrl")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAuthHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BrandId");

                    b.ToTable("BrandLgCredentials");
                });

            modelBuilder.Entity("QLS.Backend.Models.Machine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Esp32MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<string>("LgDeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<string>("ZigbeeNetworkId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Machines");
                });

            modelBuilder.Entity("QLS.Backend.Models.MachineSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualEndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CycleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExtension")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PaymentConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("PricePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("PricingMode")
                        .HasColumnType("integer");

                    b.Property<string>("RefundNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RefundStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("StoreId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TotalMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("PriceListId");

                    b.HasIndex("StoreId");

                    b.HasIndex("UserId");

                    b.ToTable("MachineSessions");
                });

            modelBuilder.Entity("QLS.Backend.Models.MachineSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddSuperWash")
                        .HasColumnType("integer");

                    b.Property<int>("Coin")
                        .HasColumnType("integer");

                    b.Property<int?>("DropCount")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("DryCycleTime")
                        .HasColumnType("integer[]");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("NonStopRinsing")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("Price")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("RinsingCount")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("RinsingTime")
                        .HasColumnType("integer[]");

                    b.Property<string>("SensingDry")
                        .HasColumnType("text");

                    b.PrimitiveCollection<string[]>("SpinSpeed")
                        .HasColumnType("text[]");

                    b.Property<string>("TopOff")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("TopOffPrice")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("TopOffTime")
                        .HasColumnType("integer[]");

                    b.Property<string>("TwinSpray")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("WashingTime")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("WaterLevel")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("MachineId")
                        .IsUnique();

                    b.ToTable("MachineSettings");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("PromotionLabel")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("PriceLists");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceListStoreType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("OverridePriority")
                        .HasColumnType("integer");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("StoreTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StoreTypeId");

                    b.HasIndex("PriceListId", "StoreTypeId")
                        .IsUnique();

                    b.ToTable("PriceListStoreTypes");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceModePerKg", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("MachineType")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MinKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MinimumPrice")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<int>("PricePer")
                        .HasColumnType("integer");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId");

                    b.ToTable("PriceModePerKgs");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceModePerSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<decimal>("MachineCapacityKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("MachineType")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasPrecision(12)
                        .HasColumnType("numeric(12,0)");

                    b.Property<Guid>("PriceListId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TimeSlotId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PriceListId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("PriceModePerSessions");

                    b.HasDiscriminator<int>("MachineType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QLS.Backend.Models.Store", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LgPinCode")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<Guid?>("StoreTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("StoreTypeId");

                    b.ToTable("Stores");
                });

            modelBuilder.Entity("QLS.Backend.Models.StoreType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("StoreTypes");
                });

            modelBuilder.Entity("QLS.Backend.Models.TimeSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid");

                    b.Property<short>("DayMask")
                        .HasColumnType("smallint");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<TimeOnly?>("StartTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("QLS.Backend.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("QLS.Backend.Models.DryerPriceMode", b =>
                {
                    b.HasBaseType("QLS.Backend.Models.PriceModePerSession");

                    b.Property<int?>("ExtensionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("MinInitialSteps")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("QLS.Backend.Models.WasherPriceMode", b =>
                {
                    b.HasBaseType("QLS.Backend.Models.PriceModePerSession");

                    b.Property<string>("CycleName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("QLS.Backend.Models.Account", b =>
                {
                    b.HasOne("QLS.Backend.Models.Brand", "Brand")
                        .WithMany("Accounts")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLS.Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("QLS.Backend.Models.BrandLgCredential", b =>
                {
                    b.HasOne("QLS.Backend.Models.Brand", "Brand")
                        .WithOne("LgCredential")
                        .HasForeignKey("QLS.Backend.Models.BrandLgCredential", "BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("QLS.Backend.Models.Machine", b =>
                {
                    b.HasOne("QLS.Backend.Models.Store", null)
                        .WithMany("Machines")
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QLS.Backend.Models.MachineSession", b =>
                {
                    b.HasOne("QLS.Backend.Models.Machine", "Machine")
                        .WithMany()
                        .HasForeignKey("MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLS.Backend.Models.PriceList", "PriceList")
                        .WithMany()
                        .HasForeignKey("PriceListId");

                    b.HasOne("QLS.Backend.Models.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLS.Backend.Models.User", "User")
                        .WithMany("MachineSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Machine");

                    b.Navigation("PriceList");

                    b.Navigation("Store");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QLS.Backend.Models.MachineSetting", b =>
                {
                    b.HasOne("QLS.Backend.Models.Machine", "Machine")
                        .WithOne("Setting")
                        .HasForeignKey("QLS.Backend.Models.MachineSetting", "MachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Machine");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceList", b =>
                {
                    b.HasOne("QLS.Backend.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceListStoreType", b =>
                {
                    b.HasOne("QLS.Backend.Models.PriceList", "PriceList")
                        .WithMany("PriceListStoreTypes")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLS.Backend.Models.StoreType", "StoreType")
                        .WithMany("PriceListStoreTypes")
                        .HasForeignKey("StoreTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");

                    b.Navigation("StoreType");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceModePerKg", b =>
                {
                    b.HasOne("QLS.Backend.Models.PriceList", "PriceList")
                        .WithMany("PriceModePerKgs")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PriceList");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceModePerSession", b =>
                {
                    b.HasOne("QLS.Backend.Models.PriceList", "PriceList")
                        .WithMany("PriceModePerSessions")
                        .HasForeignKey("PriceListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLS.Backend.Models.TimeSlot", "TimeSlot")
                        .WithMany("PriceModesPerSession")
                        .HasForeignKey("TimeSlotId");

                    b.Navigation("PriceList");

                    b.Navigation("TimeSlot");
                });

            modelBuilder.Entity("QLS.Backend.Models.Store", b =>
                {
                    b.HasOne("QLS.Backend.Models.Brand", "Brand")
                        .WithMany("Stores")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLS.Backend.Models.StoreType", "StoreType")
                        .WithMany("Stores")
                        .HasForeignKey("StoreTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Brand");

                    b.Navigation("StoreType");
                });

            modelBuilder.Entity("QLS.Backend.Models.StoreType", b =>
                {
                    b.HasOne("QLS.Backend.Models.Brand", "Brand")
                        .WithMany("StoreTypes")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("QLS.Backend.Models.TimeSlot", b =>
                {
                    b.HasOne("QLS.Backend.Models.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("QLS.Backend.Models.Brand", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("LgCredential");

                    b.Navigation("StoreTypes");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("QLS.Backend.Models.Machine", b =>
                {
                    b.Navigation("Setting");
                });

            modelBuilder.Entity("QLS.Backend.Models.PriceList", b =>
                {
                    b.Navigation("PriceListStoreTypes");

                    b.Navigation("PriceModePerKgs");

                    b.Navigation("PriceModePerSessions");
                });

            modelBuilder.Entity("QLS.Backend.Models.Store", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("QLS.Backend.Models.StoreType", b =>
                {
                    b.Navigation("PriceListStoreTypes");

                    b.Navigation("Stores");
                });

            modelBuilder.Entity("QLS.Backend.Models.TimeSlot", b =>
                {
                    b.Navigation("PriceModesPerSession");
                });

            modelBuilder.Entity("QLS.Backend.Models.User", b =>
                {
                    b.Navigation("MachineSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
